name: Template Core Build Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup PNPM
        run: npm install --global pnpm@10.7.0

      - name: Install Dependencies
        run: pnpm install

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_ACTIONS_ID }}
          private-key: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: 🔁 Configure Git with App Token
        run: |
          git config user.name "Release Bot"
          git config user.email "bot@example.com"
          git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}.git

      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          HUSKY: 0
          CI: true
        run: |
          npm run release
          node -e 'console.log(require("./package.json").version)'
