name: OET PG Schema Build Pipeline
on:
  push:
    branches:
      - main
      - fix/ET-26/prisma-generate
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  schema-pipeline:
    uses: ./.github/workflows/common.yml
    with:
      runs-on: ubuntu-latest
      gh_app_id: ${{ vars.GH_ACTIONS_ID }}
    secrets:
      gh_app_token: ${{ secrets.GH_ACTIONS_TOKEN }}
      gh_pat_write: ${{ secrets.OET_PAT_PKG_WRITE }}
